categories:
  - title: 新功能
    label: feat
  - title: Bugfix
    label: fix
  - title: 依赖更新
    label: dep
  - title: 日常维护
    label: chore
  - title: 文档
    label: docs

autolabeler:
  - label: 'feat'
    title:
      - '/feat/i'
  - label: 'fix'
    title:
      - '/fix/i'
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'docs'
    title:
      - '/docs/i'

template: |
 
 ## 更新记录

  $CHANGES
  
