categories:
  - title: 新功能
    label: feat
  - title: Bugfix
    label: fix
  - title: 依赖更新
    label: dep
  - title: 日常维护
    label: chore
  - title: 样式更新
    label: style
  - title: 文档
    label: doc

autolabeler:
  - label: 'feat'
    title:
      - '/feat/i'
  - label: 'fix'
    title:
      - '/fix/i'
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'style'
    title:
      - '/style/i'
  - label: 'doc'
    title:
      - '/doc/i'

template: |

  ## 更新记录

   $CHANGES
