export default {
  auto_filter: ['autofilter.xlsx', 'eq.xlsx', 'init.xlsx'],
  chart: [
    'chart.xlsx',
    'chart_area.xlsx',
    'chart_bar.xlsx',
    'chart_clustered.xlsx',
    'chart_column.xlsx',
    'chart_combined.xlsx',
    'chart_data_labels.xlsx',
    'chart_data_table.xlsx',
    'chart_data_tools.xlsx',
    'chart_date_axis.xlsx',
    'chart_doughnut.xlsx',
    'chart_gauge.xlsx',
    'chart_gradient.xlsx',
    'chart_line.xlsx',
    'chart_pareto.xlsx',
    'chart_pattern.xlsx',
    'chart_pie.xlsx',
    'chart_radar.xlsx',
    'chart_scatter.xlsx',
    'chart_secondary_axis.xlsx',
    'chart_stock.xlsx',
    'chart_styles.xlsx',
    'chartsheet.xlsx'
  ],
  conditional_format: [
    '3color.xlsx',
    'blank.xlsx',
    'bottom_range.xlsx',
    'conditional_format.xlsx',
    'databar.xlsx',
    'databar_number.xlsx',
    'date.xlsx',
    'iconset.xlsx',
    'simple.xlsx',
    'x14_iconset.xlsx'
  ],
  csv: ['simple.csv', 'simple.tsv'],
  font: ['custom_font.xlsx'],
  formula: [
    'Expenses01.xlsx',
    'Expenses02.xlsx',
    'Expenses03.xlsx',
    'array_formula.xlsx',
    'formula.xlsx',
    'lambda.xlsx'
  ],
  freeze: ['freeze.xlsx', 'freeze_col.xlsx', 'freeze_row.xlsx', 'panes.xlsx'],
  image: [
    'crop.xlsx',
    'image.xlsx',
    'image_group.xlsx',
    'images.xlsx',
    'img.xlsx'
  ],
  large: ['100.xlsx', '100k.xlsx', '10k.xlsx', '1k.xlsx', '关键词速查表.xlsx'],
  malformed: ['lowcase.xlsx'],
  merge: [
    'merge1.xlsx',
    'merge_cell.xlsx',
    'merge_rich_string.xlsx',
    'scroll_left.xlsx'
  ],
  numfmt: [
    '1904.xlsx',
    'aaa.xlsx',
    'aaaa.xlsx',
    'nan.xlsx',
    'number_as_text.xlsx',
    'numfmt_color.xlsx',
    'rmb.xlsx'
  ],
  outline: ['outline.xlsx', 'outline_collapsed.xlsx'],
  pivot: ['pivot_table_data.xlsx', 'simple.xlsx'],
  protect: ['protect.xlsx'],
  sheet: ['many_sheet.xlsx', 'sheet_color.xlsx', 'sheet_hide.xlsx'],
  simple: [
    'all.xlsx',
    'colRowSize.xlsx',
    'datetimes.xlsx',
    'defaultColWidth.xlsx',
    'definedName.xlsx',
    'demo.xlsx',
    'e.xlsx',
    'full.xlsx',
    'gridline.xlsx',
    'hidden.xlsx',
    'hide.xlsx',
    'hide_row_col.xlsx',
    'multipleSheet.xlsx',
    'noHeaderGrid.xlsx',
    'presetCellStyles.xlsx'
  ],
  slow: ['many_text.xlsx'],
  sparklines: ['sparklines1.xlsx', 'sparklines2.xlsx'],
  style: ['border.xlsx', 'diag_border.xlsx'],
  table: ['slicer.xlsx', 'tableFilter.xlsx', 'tables.xlsx'],
  text: [
    'auto_clip.xlsx',
    'auto_height.xlsx',
    'background.xlsx',
    'bottom.xlsx',
    'bug_1.xlsx',
    'cell_indentation.xlsx',
    'clip.xlsx',
    'fontStyle.xlsx',
    'hyperlink.xlsx',
    'link.xlsx',
    'number.xlsx',
    'rich.xlsx',
    'rich_strings.xlsx',
    'right_to_left.xlsx',
    'sharedString.xlsx',
    'textFill.xlsx',
    'textRotation.xlsx',
    'text_indent.xlsx',
    'wrap.xlsx'
  ],
  textbox: [
    'background.xlsx',
    'image_group.xlsx',
    'rich.xlsx',
    'shape.xlsx',
    'simple.xlsx',
    'textbox.xlsx'
  ],
  todo: [
    'autofit.xlsx',
    'background.xlsx',
    'comments.xlsx',
    'comments1.xlsx',
    'data_validate.xlsx',
    'defined_name.xlsx',
    'dynamic_arrays.xlsx',
    'ignore_errors.xlsx',
    'protection.xlsx'
  ]
};
