export enum UnderlineType {
  SINGLE = 'single',
  WORDS = 'words',
  DOUBLE = 'double',
  THICK = 'thick',
  DOTTED = 'dotted',
  DOTTEDHEAVY = 'dottedHeavy',
  DASH = 'dash',
  DASHEDHEAVY = 'dashedHeavy',
  DASHLONG = 'dashLong',
  DASHLONGHEAVY = 'dashLongHeavy',
  DOTDASH = 'dotDash',
  DASHDOTHEAVY = 'dashDotHeavy',
  DOTDOTDASH = 'dotDotDash',
  DASHDOTDOTHEAVY = 'dashDotDotHeavy',
  WAVE = 'wave',
  WAVYHEAVY = 'wavyHeavy',
  WAVYDOUBLE = 'wavyDouble',
  NONE = 'none'
}
